### ISSUE TITLE
Error in star cluster view

### ISSUE THREAD

**Issue by EstebanLB** [Powana/BetterGlobeMap#2]
In the star cluster view The resources chart is not visible, and I get an error.

**Comment by Powana** [comment]
Hi, by star cluster view do you mean the star map you get when pressing V? What error do you get?
I'm going to update the mod so that the indicators properly disappear when in the starmap, they're kinda useless there.

**Comment by EstebanLB** [comment]
Yeah, that map. I deacticated the mod now and forgot to capture the error. If it's not inmediatly reproducible by you, then I can try it again but it will probably be a conflict with other mod

**Comment by Powana** [comment]
Does sound like a conflict, thanks for bringing it up though. I've updated the mod and there shouldn't be any issues with the starmap now.
