### ISSUE TITLE
Tried to highlight coal nodes

### ISSUE THREAD

**Issue by Lt-Sparky** [Powana/BetterGlobeMap#4]
![betterglobemap](https://user-images.githubusercontent.com/85095233/174457190-b26fdde5-7268-47a6-a0a9-89a43bcc951d.png)

It happen when i tried to highlight coal nodes while in the globe view

**Comment by masterofchi** [comment]
I get the same error whenever I try to highlight or scroll to the nearest vein - and not only coal but every vein.

Seems like this functionality got broken in the latest DSP update - some other mods had issues too.
