### ISSUE TITLE
Error thrown when clicking highlight and or show nearest vein

### ISSUE THREAD

**Issue by mikeloeven** [Powana/BetterGlobeMap#5]
Neither the highlight or show nearest vein buttons function currently Error thrown is 
error as it appears in game 
![image](https://user-images.githubusercontent.com/2266606/185716836-9266f343-a778-49b9-8ed9-f0ef612dee85.png)

BEPINEX log shows this errors as well 

[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000024 (from typeref, class/assembly VeinGroup, )
Stack trace:
BetterGlobeMap.BetterGlobeMap+<>c__DisplayClass19_0.<UIPlanetDetail_Postfix>b__1 (System.Int32 id) (at <2ac6e95337f047f28bccec9940749ac2>:0)
UIButton.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <cd5920ceb8c14a789179463b23b5033f>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <32bd6c8a2dd3414ca080d595da90bbab>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <32bd6c8a2dd3414ca080d595da90bbab>:0)
UnityEngine.EventSystems.EventSystem:Update()

[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000024 (from typeref, class/assembly VeinGroup, )
Stack trace:
BetterGlobeMap.BetterGlobeMap+<>c__DisplayClass19_0.<UIPlanetDetail_Postfix>b__0 (System.Int32 id) (at <2ac6e95337f047f28bccec9940749ac2>:0)
UIButton.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <cd5920ceb8c14a789179463b23b5033f>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <32bd6c8a2dd3414ca080d595da90bbab>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <32bd6c8a2dd3414ca080d595da90bbab>:0)
UnityEngine.EventSystems.EventSystem:Update()

**Comment by mikeloeven** [comment]
On a side note this could be a mod conflict as I am running Galactic Scale world gen 
Update: Ruled this out by testing with a new game with GS disabled issue persists

**Comment by Powana** [comment]
Fixed in 1.0.5
